# Generated by Django 5.2.5 on 2025-09-13 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookshelf", "0002_alter_customuser_managers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={
                "ordering": ["-created_at", "title"],
                "permissions": (
                    ("can_view", "Can view book details"),
                    ("can_create", "Can create new books"),
                    ("can_edit", "Can edit existing books"),
                    ("can_delete", "Can delete books"),
                ),
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
            },
        ),
    ]
