"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-5z=8!w^clp1t^84!=d9$sr(d4ka(t%euk+%6!e0k0+%#*t_rqa"

# SECURITY WARNING: don't run with debug turned on in production!
# Set to False in production for security
DEBUG = True

# Security: Configure allowed hosts for production
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0', 'testserver']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "bookshelf",
    "relationship_app",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "bookshelf.middleware.SecurityLoggingMiddleware",  # Custom security logging
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "bookshelf.middleware.SecurityHeadersMiddleware",  # Custom security headers
]

ROOT_URLCONF = "LibraryProject.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "LibraryProject.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom User Model
AUTH_USER_MODEL = 'bookshelf.CustomUser'

LOGIN_REDIRECT_URL = "member_view"
LOGOUT_REDIRECT_URL = "login"

# =============================================================================
# SECURITY CONFIGURATIONS
# =============================================================================

# Security: HTTPS and SSL Settings
# Configure for production HTTPS deployment
SECURE_SSL_REDIRECT = True  # Redirect all HTTP requests to HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Security: HTTP Strict Transport Security (HSTS)
# Instruct browsers to only access the site via HTTPS
SECURE_HSTS_SECONDS = 31536000  # 1 year (31536000 seconds)
SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # Include all subdomains in HSTS policy
SECURE_HSTS_PRELOAD = True  # Allow HSTS preloading in browsers

# Security: Additional HTTPS settings
SECURE_REDIRECT_EXEMPT = []  # URLs that should not be redirected to HTTPS
SECURE_SSL_HOST = None  # Custom SSL host (if different from ALLOWED_HOSTS)

# Security: Cookie Security
# Enforce secure cookies for HTTPS connections
CSRF_COOKIE_SECURE = True  # CSRF cookies only sent over HTTPS
SESSION_COOKIE_SECURE = True  # Session cookies only sent over HTTPS
CSRF_COOKIE_HTTPONLY = True  # Prevent JavaScript access to CSRF cookie
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to session cookie
CSRF_COOKIE_SAMESITE = 'Strict'  # CSRF cookie SameSite attribute (Strict for better security)
SESSION_COOKIE_SAMESITE = 'Strict'  # Session cookie SameSite attribute (Strict for better security)

# Security: Additional cookie settings
CSRF_COOKIE_AGE = 31449600  # 1 year CSRF cookie age
CSRF_USE_SESSIONS = False  # Use cookies for CSRF tokens (not sessions)
CSRF_FAILURE_VIEW = 'django.views.csrf.csrf_failure'

# Security: Browser Security Headers
# Prevent various types of attacks through HTTP headers
SECURE_BROWSER_XSS_FILTER = True  # Enable browser's XSS filtering
SECURE_CONTENT_TYPE_NOSNIFF = True  # Prevent MIME type sniffing attacks
X_FRAME_OPTIONS = 'DENY'  # Prevent clickjacking attacks (DENY is most secure)

# Security: Additional security headers
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'  # Control referrer information
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'  # Prevent cross-origin attacks

# Security: Content Security Policy (CSP)
# Define which sources are allowed for different types of content
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = ("'self'", "'unsafe-inline'")  # Allow inline scripts for Django admin
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'")  # Allow inline styles for Django admin
CSP_IMG_SRC = ("'self'", "data:", "https:")
CSP_FONT_SRC = ("'self'",)
CSP_CONNECT_SRC = ("'self'",)
CSP_FRAME_ANCESTORS = ("'none'",)  # Prevent embedding in frames
CSP_BASE_URI = ("'self'",)
CSP_OBJECT_SRC = ("'none'",)

# Security: Additional Security Headers
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'

# Security: Password Security
# Enhanced password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 8,  # Minimum 8 characters
        }
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Security: Session Security
SESSION_COOKIE_AGE = 3600  # 1 hour session timeout
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Expire session when browser closes
SESSION_SAVE_EVERY_REQUEST = True  # Save session on every request

# Security: CSRF Protection
CSRF_COOKIE_AGE = 31449600  # 1 year CSRF cookie age
CSRF_USE_SESSIONS = False  # Use cookies for CSRF tokens
CSRF_FAILURE_VIEW = 'django.views.csrf.csrf_failure'

# Security: File Upload Security
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB max file size
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB max data upload
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000  # Max number of form fields

# Security: Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'security.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django.security': {
            'handlers': ['file', 'console'],
            'level': 'WARNING',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['file', 'console'],
            'level': 'WARNING',
            'propagate': True,
        },
    },
}

# Security: Database Security
# Use environment variables for database credentials in production
DATABASES['default']['OPTIONS'] = {
    'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
}

# Security: Email Security (for production)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Console backend for development
# In production, use:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'your-smtp-server.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your-email@example.com'
# EMAIL_HOST_PASSWORD = 'your-password'

# Security: Cache Security
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
            'CULL_FREQUENCY': 3,
        }
    }
}

# Security: Static Files Security
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# Security: Media Files Security
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

# Security: Admin Security
ADMIN_URL = 'admin/'  # Custom admin URL to hide default admin path

# Security: Development vs Production Settings
if DEBUG:
    # Development-specific security settings
    INTERNAL_IPS = ['127.0.0.1', 'localhost']
    
    # For development, we can relax some HTTPS settings if needed
    # Uncomment the following lines if you need to test without HTTPS in development
    # SECURE_SSL_REDIRECT = False
    # CSRF_COOKIE_SECURE = False
    # SESSION_COOKIE_SECURE = False
    # SECURE_HSTS_SECONDS = 0
else:
    # Production-specific security settings
    # These settings are already configured above for production use
    # Additional production-only settings can be added here
    
    # Ensure all security settings are enforced in production
    SECURE_SSL_REDIRECT = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # Production-specific logging
    LOGGING['handlers']['file']['filename'] = BASE_DIR / 'logs' / 'production.log'
