# Generated by Django 5.2.5 on 2025-09-13 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("relationship_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={
                "ordering": ["name"],
                "permissions": (
                    ("can_view", "Can view author details"),
                    ("can_create", "Can create new authors"),
                    ("can_edit", "Can edit existing authors"),
                    ("can_delete", "Can delete authors"),
                ),
                "verbose_name": "Author",
                "verbose_name_plural": "Authors",
            },
        ),
        migrations.AlterModelOptions(
            name="library",
            options={
                "ordering": ["name"],
                "permissions": (
                    ("can_view", "Can view library details"),
                    ("can_create", "Can create new libraries"),
                    ("can_edit", "Can edit existing libraries"),
                    ("can_delete", "Can delete libraries"),
                ),
                "verbose_name": "Library",
                "verbose_name_plural": "Libraries",
            },
        ),
    ]
