# Generated by Django 5.2.5 on 2025-09-07 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("relationship_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={
                "ordering": ["title"],
                "permissions": (
                    ("can_add_book", "Can add book"),
                    ("can_change_book", "Can change book"),
                    ("can_delete_book", "Can delete book"),
                ),
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
            },
        ),
    ]
